eval $(ssh-agent) &> /dev/null
ssh-add /root/.ssh/id_rsa &> /dev/null

# init known_hosts
if [ ! -s ~/.ssh/known_hosts ]; then
    echo > ~/.ssh/known_hosts
    # Get nodes list
    # Wait nodes[n1,n2...] register hostname
    if [ ! -s /var/jepsen/shared/nodes ]; then
      sleep 1
    fi
    sort -V /var/jepsen/shared/nodes > ~/nodes
    # Scan SSH keys
    while read node; do
      ssh-keyscan -t rsa $node >> ~/.ssh/known_hosts
    done <~/nodes
fi

cat <<EOF
Welcome to Jepsen on Docker
===========================

This container runs the Jepsen tests in sub-containers.

You are currently in the base dir of the git repo for Jepsen.
If you modify the core jepsen library make sure you "lein install" it so other tests can access.

To run a test:
   cd /jepsen/jepsen && lein run test --concurrency 10 -w set
EOF

cd /jepsen/jepsen
