#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import logging
import os
import signal
import subprocess
import sys

CUR_FILE_DIR = os.path.dirname(os.path.realpath(__file__))
DEFAULT_RAFTKEEPER_ROOT = os.path.abspath(os.path.join(CUR_FILE_DIR, "../../"))
CURRENT_WORK_DIR = os.getcwd()
CONTAINER_NAME = "raftkeeper_integration_tests"

CONFIG_DIR_IN_REPO = "programs/server"
INTERGATION_DIR_IN_REPO = "tests/integration"
SRC_DIR_IN_REPO = "src"
RAFT_BENCHMARK_DIR_IN_REPO = "benchmark/raft-benchmark"

DIND_INTEGRATION_TESTS_IMAGE_NAME = "raftkeeper/raftkeeper-integration-tests-runner"  # run raft-benchmark


def check_args_and_update_paths(args):
    if args.raftkeeper_root:
        if not os.path.isabs(args.raftkeeper_root):
            RAFTKEEPER_ROOT = os.path.abspath(args.raftkeeper_root)
        else:
            RAFTKEEPER_ROOT = args.raftkeeper_root
    else:
        logging.debug("RaftKeeper root is not set. Will use {}".format(DEFAULT_RAFTKEEPER_ROOT))
        RAFTKEEPER_ROOT = DEFAULT_RAFTKEEPER_ROOT

    if not os.path.isabs(args.binary):
        args.binary = os.path.abspath(os.path.join(CURRENT_WORK_DIR, args.binary))

    if args.old_binary:
        if not os.path.isabs(args.old_binary):
            args.old_binary = os.path.abspath(os.path.join(CURRENT_WORK_DIR, args.old_binary))
    else:
        args.old_binary = args.binary
        logging.debug("old_binary is not set. Will use {}".format(args.old_binary))

    if args.base_configs_dir:
        if not os.path.isabs(args.base_configs_dir):
            args.base_configs_dir = os.path.abspath(os.path.join(CURRENT_WORK_DIR, args.base_configs_dir))
    else:
        args.base_configs_dir = os.path.abspath(os.path.join(RAFTKEEPER_ROOT, CONFIG_DIR_IN_REPO))
        logging.debug("Base configs dir is not set. Will use {}".format(args.base_configs_dir))

    if args.cases_dir:
        if not os.path.isabs(args.cases_dir):
            args.cases_dir = os.path.abspath(os.path.join(CURRENT_WORK_DIR, args.cases_dir))
    else:
        args.cases_dir = os.path.abspath(os.path.join(RAFTKEEPER_ROOT, INTERGATION_DIR_IN_REPO))
        logging.debug("Cases dir is not set. Will use {}".format(args.cases_dir))

    if args.src_dir:
        if not os.path.isabs(args.src_dir):
            args.src_dir = os.path.abspath(os.path.join(CURRENT_WORK_DIR, args.src_dir))
    else:
        args.src_dir = os.path.abspath(os.path.join(RAFTKEEPER_ROOT, SRC_DIR_IN_REPO))
        logging.debug("src dir is not set. Will use {}".format(args.src_dir))

    if args.raft_benchmark_dir:
        if not os.path.isabs(args.raft_benchmark_dir):
            args.raft_benchmark_dir = os.path.abspath(os.path.join(CURRENT_WORK_DIR, args.raft_benchmark_dir))
    else:
        args.raft_benchmark_dir = os.path.abspath(os.path.join(RAFTKEEPER_ROOT, RAFT_BENCHMARK_DIR_IN_REPO))
        logging.debug("raft-benchmark dir is not set. Will use {}".format(args.raft_benchmark_dir))

    logging.debug(
        "base_configs_dir: {},  binary: {}, cases_dir: {} ".format(args.base_configs_dir, args.binary, args.cases_dir))

    for path in [args.binary, args.base_configs_dir, args.cases_dir, RAFTKEEPER_ROOT]:
        if not os.path.exists(path):
            raise Exception("Path {} doesn't exist".format(path))

    if not os.path.exists(os.path.join(args.base_configs_dir, "config.xml")):
        raise Exception("No configs.xml in {}".format(args.base_configs_dir))


def docker_kill_handler_handler(signum, frame):
    subprocess.check_call(
        'docker kill $(docker ps -a -q --filter name={name} --format="{{{{.ID}}}}")'.format(name=CONTAINER_NAME),
        shell=True)
    raise KeyboardInterrupt("Killed by Ctrl+C")


signal.signal(signal.SIGINT, docker_kill_handler_handler)

# Integration tests runner should allow to run tests on several versions of RaftKeeper.
# Integration tests should be portable.
# To run integration tests following artfacts should be sufficient:
#   - raftkeeper binaries (env RAFTKEEPER_TESTS_SERVER_BIN_PATH or --binary arg)
#   - raftkeeper default configs(config.xml, users.xml) from same version as binary
#     (env RAFTKEEPER_TESTS_BASE_CONFIG_DIR or --base-configs-dir arg)
#   - odbc bridge binary (env RAFTKEEPER_TESTS_ODBC_BRIDGE_BIN_PATH or --bridge-binary arg)
#   - tests/integration directory with all test cases and configs (env RAFTKEEPER_TESTS_INTEGRATION_PATH or --cases-dir)
#
# 1) --raftkeeper-root is only used to determine other paths on default places
# 2) path of runner script is used to determine paths for trivial case, when we run it from repository

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format='%(asctime)s %(message)s')
    parser = argparse.ArgumentParser(description="RaftKeeper integration tests runner")

    parser.add_argument(
        "--binary",
        default=os.environ.get("RAFTKEEPER_TESTS_SERVER_BIN_PATH",
                               os.environ.get("RAFTKEEPER_TESTS_CLIENT_BIN_PATH", "/usr/bin/raftkeeper")),
        help="Path to raftkeeper binary. For example /usr/bin/raftkeeper")

    parser.add_argument(
        "--old-binary",
        default=os.environ.get("RAFTKEEPER_TESTS_OLD_SERVER_BIN_PATH",
                               os.environ.get("RAFTKEEPER_TESTS_OLD_SERVER_BIN_PATH", "/usr/bin/raftkeeper")),
        help="Path to old raftkeeper binary. For example /usr/bin/raftkeeper")

    parser.add_argument(
        "--base-configs-dir",
        default=os.environ.get("RAFTKEEPER_TESTS_BASE_CONFIG_DIR"),
        help="Path to raftkeeper base configs directory with config.xml/users.xml")

    parser.add_argument(
        "--cases-dir",
        default=os.environ.get("RAFTKEEPER_TESTS_INTEGRATION_PATH"),
        help="Path to integration tests cases and configs directory. For example tests/integration in repository")

    parser.add_argument(
        "--src-dir",
        default=os.environ.get("RAFTKEEPER_SRC_DIR"),
        help="Path to the 'src' directory in repository. Used to provide schemas (e.g. *.proto) for some tests when "
             "those schemas are located in the 'src' directory")

    parser.add_argument(
        "--raft-benchmark-dir",
        default=os.environ.get("RAFTKEEPER_RAFT_BENCHMARK_DIR"),
        help="Path to the 'benchmark/raft-benchmark' directory in repository. Used to provide schemas (e.g. *.proto) "
             "for some tests when those schemas are located in the 'benchmark/raft-benchmark' directory")

    parser.add_argument(
        "--raftkeeper-root",
        help="Path to repository root folder. Used to take configuration from repository default paths.")

    parser.add_argument(
        "--command",
        default='',
        help="Set it to run some other command in container (for example bash)")

    parser.add_argument(
        "--docker-image-version",
        default="latest",
        help="Version of docker image which runner will use to run tests")

    parser.add_argument(
        "--docker-compose-images-tags",
        action="append",
        help="Set non-default tags for images used in docker compose recipes(yandex/my_container:my_tag)")

    parser.add_argument(
        "--use-net-host",
        action="store_true",
        help="Whether use host net in runner, if false, will use bridge host.")

    parser.add_argument(
        "--tsan-options",
        default="halt_on_error=1 history_size=7",
        help="TSAN_OPTIONS which will be transferred to raftkeeper instance.")

    parser.add_argument(
        "--msan-options",
        default="abort_on_error=1",
        help="MSAN_OPTIONS which will be transferred to raftkeeper instance.")

    parser.add_argument(
        "--asan-options",
        default="",
        help="ASAN_OPTIONS which will be transferred to raftkeeper instance.")

    parser.add_argument(
        "--ubsan-options",
        default="print_stacktrace=1",
        help="UBSAN_OPTIONS which will be transferred to raftkeeper instance.")

    parser.add_argument('pytest_args', nargs='*', help="args for pytest command")

    args = parser.parse_args()

    check_args_and_update_paths(args)

    net = ""
    if args.use_net_host:
        net = "--net=host"

    env_tags = ""

    if args.docker_compose_images_tags is not None:
        for img_tag in args.docker_compose_images_tags:
            [image, tag] = img_tag.split(":")
            if image == "raftkeeper/raftkeeper-integration-tests":
                env_tags += "-e {}={} ".format("DOCKER_BASE_TAG", tag)
            else:
                logging.info("Unknown image {}".format(image))

    # create named volume which will be used inside to store images and other docker related files,
    # to avoid reloading it every time
    #
    # should be removed manually when not needed
    subprocess.check_call('docker volume create {name}_volume'.format(name=CONTAINER_NAME), shell=True)

    # enable tty mode & interactive for docker if we have real tty
    tty = ""
    if sys.stdout.isatty() and sys.stdin.isatty():
        tty = "-it"

    cmd = 'docker run {net} {tty} --rm --name {name} --privileged --volume={bin}:/raftkeeper \
        --volume={base_cfg}:/raftkeeper-config --volume={cases_dir}:/RaftKeeper/tests/integration \
        --volume={old_bin}:/raftkeeper_old --volume={cases_dir}/../sanitizers:/RaftKeeper/tests/sanitizers \
        --volume={name}_volume:/var/lib/docker {env_tags} \
        -e TSAN_OPTIONS=\'{tsan_options}\' \
        -e MSAN_OPTIONS=\'{msan_options}\' \
        -e ASAN_OPTIONS=\'{asan_options}\' \
        -e UBSAN_OPTIONS=\'{ubsan_options}\' \
        -e SANITIZERS_DIR=\'/RaftKeeper/tests/sanitizers\' \
        -e PYTEST_OPTS=\'{opts}\' {img} {command}'.format(
        net=net,
        tty=tty,
        bin=args.binary,
        base_cfg=args.base_configs_dir,
        cases_dir=args.cases_dir,
        src_dir=args.src_dir,
        raft_benchmark_dir=args.raft_benchmark_dir,
        old_bin=args.old_binary,
        env_tags=env_tags,
        opts=' '.join(args.pytest_args),
        img=DIND_INTEGRATION_TESTS_IMAGE_NAME + ":" + args.docker_image_version,
        name=CONTAINER_NAME,
        command=args.command,
        tsan_options=args.tsan_options,
        msan_options=args.msan_options,
        asan_options=args.asan_options,
        ubsan_options=args.ubsan_options
    )

    print(("Running pytest container as: '" + cmd + "'."))
    subprocess.check_call(cmd, shell=True)
