name: Build and Test on Ubuntu/ARM64

on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  run-arch64:
    runs-on: ubuntu-22.04-arm # Use an ARM64 runner
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare environment
        run: bash .github/workflows/prepare-env.sh 18

      - name: Generate Makefile
        run: |
          export CC=`which clang` CXX=`which clang++`
          cmake -G Ninja -B ./build -DCMAKE_BUILD_TYPE=${{ inputs.build_type }}

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: ninja -j 10

      - name: Run unit tests
        working-directory: ${{github.workspace}}/build
        run: ./src/rk_unit_tests --gtest_color=yes
