name: build-and-test

on:
  push:
    branches: [ "ci-test" ]
  pull_request:
    branches: [ "ci-test" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install tools
      run: sudo apt install -y ninja-build ccache

    - name: Generate Makefile
      run: export CC=`which clang` CXX=`which clang++` && cmake -G Ninja -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: ninja -j 10

#    - name: Run unit Tests
#      working-directory: ${{github.workspace}}/build
#      run: ./src/unit_tests_dbms --gtest_color=yes

    - name: Run integration Tests
      working-directory: ${{github.workspace}}/tests/integration
#      run:  ./runner --binary ${{github.workspace}}/build/programs/raftkeeper  --base-configs-dir ${{github.workspace}}/programs/server test_multinode_simple \
      run: bash ${{github.workspace}}/.github/workflows/run-integration-test.sh ${{github.workspace}}/tests/integration
