name: build-and-test-macos

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "**/docs/**"
      - "**/LICENSE"
      - "**/NOTICE"
      - "**/benchmark/**"
      - "version.txt"
      - "build.sh"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "**.md"
      - "**/docs/**"
      - "**/LICENSE"
      - "**/NOTICE"
      - "**/benchmark/**"
      - "version.txt"
      - "build.sh"

  workflow_dispatch:
    inputs:
      pr:
        description: "Pull request#"
        required: false

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-and-test:
    name: "macos clang"
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install tools
        run: brew install ninja ccache cmake llvm@13

      - name: Generate Makefile
        run: export CC=$(brew --prefix llvm@13)/bin/clang CXX=$(brew --prefix llvm@13)/bin/clang++ && cmake -G Ninja -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: ninja -j 10

      - name: Run unit Tests
        working-directory: ${{github.workspace}}/build
        run: ./src/unit_tests_dbms --gtest_color=yes
