name: Build and Test macOS

on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  run:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install tools
        run: brew install ninja ccache cmake llvm@17

      - name: Generate Makefile
        run: export CC=$(brew --prefix llvm@17)/bin/clang CXX=$(brew --prefix llvm@17)/bin/clang++ && cmake -G Ninja -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: ninja -j 10

      - name: Run unit tests
        working-directory: ${{github.workspace}}/build
        run: ./src/rk_unit_tests --gtest_color=yes
