name: Unit Test

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      sanitize:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: unit-test-binary-${{ inputs.sanitize }}
          path: build/src/

      - name: Run unit tests
        working-directory: ${{ github.workspace }}/build
        run: sudo chmod 755 ./src/rk_unit_tests && ./src/rk_unit_tests --gtest_color=yes --gtest_output=xml:unit-test-report-${{ inputs.sanitize }}.xml

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report-${{ inputs.sanitize }}.xml
          path: build/unit-test-report-${{ inputs.sanitize }}.xml
